/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.RegistroVideoClub;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Pelicula;
import sql.Conexion;

/**
 *
 * @author Alumno
 */
public class Inicio extends javax.swing.JFrame {
        RegistroVideoClub rp;
        Pelicula peliculaParametro;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(this);
        rp = new RegistroVideoClub();
        peliculaParametro = new Pelicula();
        cargarCMB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txCodigo = new javax.swing.JTextField();
        txNombre = new javax.swing.JTextField();
        txPrecio = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JToggleButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checkFormato = new javax.swing.JCheckBox();
        cmbDescripcion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtListar = new javax.swing.JTable();
        lb4kEditar = new javax.swing.JPanel();
        txCodigoEditar = new javax.swing.JTextField();
        btnBuscarCodigo = new javax.swing.JToggleButton();
        txNombreEditar = new javax.swing.JTextField();
        txPrecioEditar = new javax.swing.JTextField();
        checkFormatoE = new javax.swing.JCheckBox();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lbNombreEditar = new javax.swing.JLabel();
        lbPrecioEditar = new javax.swing.JLabel();
        lbDescripcionEditar = new javax.swing.JLabel();
        btnLimpiarEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbDescripcion1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VIDEO CLUB BUSTER");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setText("CÓDICO");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("PRECIO");

        jLabel4.setText("FORMATO 4k");

        jLabel5.setText("DESCRIPCIÓN");

        cmbDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDescripcionActionPerformed(evt);
            }
        });

        jLabel7.setText("10000-99999");

        jLabel8.setText("Mayor 3 Caracteres");

        jLabel9.setText("Mayor a 1000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkFormato)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(txNombre)
                                .addComponent(txPrecio))
                            .addComponent(cmbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(checkFormato))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnAgregar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "PRECIO", "FORMATO", "DESCRIPCION"
            }
        ));
        jScrollPane2.setViewportView(jtListar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPanel3);

        btnBuscarCodigo.setText("Buscar Codigo");
        btnBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCodigoActionPerformed(evt);
            }
        });

        checkFormatoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFormatoEActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lbNombreEditar.setText("NOMBRE");

        lbPrecioEditar.setText("PRECIO");

        lbDescripcionEditar.setText("DESCRIPCION");

        btnLimpiarEditar.setText("Limpiar");
        btnLimpiarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEditarActionPerformed(evt);
            }
        });

        jLabel6.setText("4k");

        cmbDescripcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDescripcion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lb4kEditarLayout = new javax.swing.GroupLayout(lb4kEditar);
        lb4kEditar.setLayout(lb4kEditarLayout);
        lb4kEditarLayout.setHorizontalGroup(
            lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lb4kEditarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lb4kEditarLayout.createSequentialGroup()
                        .addComponent(checkFormatoE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(lb4kEditarLayout.createSequentialGroup()
                        .addComponent(txCodigoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lb4kEditarLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnBuscarCodigo)
                                .addContainerGap(156, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lb4kEditarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnLimpiarEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35))))
                    .addGroup(lb4kEditarLayout.createSequentialGroup()
                        .addGroup(lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDescripcion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txPrecioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombreEditar)
                            .addComponent(lbPrecioEditar)
                            .addComponent(lbDescripcionEditar))
                        .addContainerGap())))
        );
        lb4kEditarLayout.setVerticalGroup(
            lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lb4kEditarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCodigoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCodigo))
                .addGap(28, 28, 28)
                .addGroup(lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombreEditar))
                .addGap(18, 18, 18)
                .addGroup(lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPrecioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecioEditar))
                .addGap(16, 16, 16)
                .addGroup(lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescripcionEditar)
                    .addComponent(cmbDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(lb4kEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkFormatoE)
                    .addComponent(btnEliminar)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarEditar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar", lb4kEditar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkFormatoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFormatoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkFormatoEActionPerformed

    private void cmbDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDescripcionActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
      if (validarDocumento())
        if (tfLleno(txCodigo.getText()))
        if (tfLleno(txNombre.getText()))
        if (tfLleno(txPrecio.getText())){
            Pelicula pelicula = new Pelicula();
            
            pelicula.setCodigo(Integer.parseInt(txCodigo.getText()));
            if(pelicula.getCodigo()>= 10000 && pelicula.getCodigo()<= 99999){
                pelicula.setNombre(this.txNombre.getText().trim());
                if(pelicula.getNombre().length()>3){
                    pelicula.setPrecio(Integer.parseInt(this.txPrecio.getText()));
                    if(pelicula.getPrecio()> 1000){
                        String aux="N";
                        if (this.checkFormato.isSelected())
                            aux="S";
                        pelicula.setFormato(aux);
                        pelicula.setId_categoria(this.cmbDescripcion.getSelectedIndex());
                        pelicula.setActivo(true);  
                    }else{
                        javax.swing.JOptionPane.showMessageDialog(this,"Valor debe ser mayor a 1000  ");
                        }
                 }else{
                        javax.swing.JOptionPane.showMessageDialog(this,"Nombre debe ser Mayor a 3 Caracteres");
                        }   
            }else{
                javax.swing.JOptionPane.showMessageDialog(this,"Rango de Codigo 10000-99999");
                }
            if(new RegistroVideoClub().agregarPelicula(pelicula)){
                javax.swing.JOptionPane.showMessageDialog(this,"Registro Grabado!!");
            }else{
                javax.swing.JOptionPane.showMessageDialog(this,"No se grabo!!");
            }
            this.limpiarPestañaUno();
        }  
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            try {
                mostrarDatos();  // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCodigoActionPerformed
        try {
            int codigo =Integer.parseInt(this.txCodigoEditar.getText().trim());
            Pelicula pelicula= new RegistroVideoClub().buscarPorCodigo(codigo);
            if(pelicula==null){
                javax.swing.JOptionPane.showMessageDialog(this,"No hay registros para el codigo: "+codigo);
            }else{
            this.txNombreEditar.setText(pelicula.getNombre());
            this.txPrecioEditar.setText(String.valueOf(pelicula.getPrecio()));
            //this.cmbDescripcion1.setSelectedIndex(pelicula.getId_categoria());
            cargarCMBBuscar(pelicula,pelicula.getId_categoria());
            if (pelicula.getFormato().equals("S")){
                this.checkFormatoE.setSelected(true);
            }else{
                checkFormatoE.setSelected(false);
            }
            
            
            }
            } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "No Ingreso Ningun Código");
        
        }
            
    }//GEN-LAST:event_btnBuscarCodigoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    limpiarPestañaUno();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnLimpiarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEditarActionPerformed
        limpiarPestañatres();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        try {
        
        peliculaParametro.setCodigo(Integer.parseInt(this.txCodigoEditar.getText()));
        boolean respuesta = rp.EliminarPelicula(peliculaParametro);
        if (respuesta) {
            JOptionPane.showMessageDialog(this, "Eliminado Correctamente :)");
        }else{
            JOptionPane.showMessageDialog(this, "Error al Eliminar :(");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar Datos ");
        }
       
        this.limpiarPestañatres();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
          try {
            peliculaParametro.setCodigo(Integer.parseInt(this.txCodigoEditar.getText()));
            peliculaParametro.setNombre(this.txNombreEditar.getText().trim());
            peliculaParametro.setPrecio(Integer.parseInt(this.txPrecioEditar.getText()));
            peliculaParametro.setId_categoria(this.cmbDescripcion1.getSelectedIndex());
            String aux="N";
            if (this.checkFormatoE.isSelected())
                aux="S";
           peliculaParametro.setFormato(aux);
           boolean respuesta = rp.ActualizarPelicula(peliculaParametro);
           System.out.println(respuesta);
        if (respuesta) {
            JOptionPane.showMessageDialog(this, "Modificado Correctamente :)");
        }else{
            JOptionPane.showMessageDialog(this, "Error al Modificar :(");
        }
            this.limpiarPestañatres();
            } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cmbDescripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDescripcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDescripcion1ActionPerformed
 private boolean validarDocumento() {
        
        boolean aux = false;
        if (cmbDescripcion.getSelectedIndex() > 0 ) {
                aux = true;
            } else{
               JOptionPane.showMessageDialog(this,"Debe Seleccionar Categoria" );
                    }
        return aux;
    }
    
    private boolean tfLleno(String valor) {
        boolean aux = false;
        if (valor.equals(""))
            JOptionPane.showMessageDialog(this,"Debe LLenar Formulario" );
        else
            aux = true;
        return aux;
    }
    
    private void limpiarPestañaUno(){
       txCodigo.setText("");
       txNombre.setText("");
       txPrecio.setText("");
       checkFormato.setSelected(false);
       cmbDescripcion.setSelectedIndex(0);
         
    }
    private void limpiarPestañatres(){
        txCodigoEditar.setText("");
        txNombreEditar.setText("");
        txPrecioEditar.setText("");
        cmbDescripcion1.setSelectedIndex(0);
        checkFormatoE.setSelected(false);
    
    
    }
    
    public ResultSet sql_query(String query) {
        Conexion  cc = new Conexion();
        Connection cn = cc.getConexion();
        if (cn == null) {
            JOptionPane.showMessageDialog(this, "No conectado :(");
        } else {
            //JOptionPane.showMessageDialog(this, "Conectado :)");
            try {
                Statement stm = cn.createStatement();
                ResultSet rs = stm.executeQuery(query);
                return rs;

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage());
            }
        }
        return null;
    }
    
    
    public void mostrarDatos() throws SQLException {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("PRECIO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("FORMATO");
               
        jtListar.setModel(modelo);
        String[] arreglo = new String[5];

        ResultSet rs = sql_query("SELECT PELICULA.CODIGO, PELICULA.NOMBRE, PELICULA.PRECIO, CATEGORIA.DESCRIPCION,PELICULA.FORMATO\n" +
"FROM PELICULA,CATEGORIA WHERE PELICULA.activo=1 AND PELICULA.ID_CATEGORIA=CATEGORIA.ID" );
        while (rs.next()) {
            arreglo[0] = rs.getString(1);
            arreglo[1] = rs.getString(2);
            arreglo[2] = rs.getString(3);
            arreglo[3] = rs.getString(4);
            if(rs.getString(5).equals("S")){
                arreglo[4] = "4K";
            } else {
                arreglo[4] = "Sin 4K";
            }
            modelo.addRow(arreglo);
        }
        jtListar.setModel(modelo);
    }
    
    
    public void cargarCMB(){
            try {
                Connection con = Conexion.getConexion();
            if (con != null) {
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("SELECT * FROM categoria WHERE activo=1");
                cmbDescripcion.removeAllItems();
                while(rs.next()){
                    this.cmbDescripcion.addItem(rs.getString("descripcion"));
                
                }
            }
            con.close();
            } catch (Exception e) {
               
            }
}
    
    
    
     public void cargarCMBBuscar(Pelicula p, int seleccion){
           try {
                Connection con = Conexion.getConexion();
            if (con != null) {
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("SELECT * FROM categoria WHERE activo=1 ");
                cmbDescripcion1.removeAllItems();
                while(rs.next()){
                    this.cmbDescripcion1.addItem(rs.getString("descripcion"));
                }
                cmbDescripcion1.setSelectedIndex(seleccion);
            }
            con.close();
            } catch (Exception e) {
               
            }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAgregar;
    private javax.swing.JToggleButton btnBuscarCodigo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarEditar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JCheckBox checkFormato;
    private javax.swing.JCheckBox checkFormatoE;
    private javax.swing.JComboBox<String> cmbDescripcion;
    private javax.swing.JComboBox<String> cmbDescripcion1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jtListar;
    private javax.swing.JPanel lb4kEditar;
    private javax.swing.JLabel lbDescripcionEditar;
    private javax.swing.JLabel lbNombreEditar;
    private javax.swing.JLabel lbPrecioEditar;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txCodigoEditar;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txNombreEditar;
    private javax.swing.JTextField txPrecio;
    private javax.swing.JTextField txPrecioEditar;
    // End of variables declaration//GEN-END:variables
}
